[metadata]
name = rxf
version = 0.0.1
description = RadarXFormer
author = Anonymous Authors
license = Apache-2.0
license_file = LICENSE
platforms = linux

[options]
packages = rxf
install_requires = 
	deepspeed<=0.13.0
	matplotlib
	numpy
	open3d
	opencv-python
	scipy
	sympy
	tensorboard
	torch_tb_profiler
	tqdm
	pypcd
	# pypcd @ https://github.com/DanielPollithy/pypcd/archive/master.zip
	# PyTorch3D has no matching PyPI distribution for this CUDA/PyTorch stack.
	# Install the vendored ./pytorch3d-stable package separately.
package_dir = =src
python_requires = >=3.8

[flake8]
max-line-length = 99
